mybatis:
  type-aliases-package: com.rp.mall.mapper
spring:
  datasource:
    url: jdbc:mysql:///heima?serverTimezone=Asia/Shanghai
    username: root
    password: rp666
  mail:
    host: smtp.qq.com
    port: 587
    username: 614523473@qq.com
    password: pjambmhhehnfbcae
    default-encoding: utf-8
    spring:
      mail:
        properties:
          mail:
            debug: true
            smtp:
              socketFactory:
                class: javax.net.ssl.SSLSocketFactory
server:
  port: 8081

